# Generated by Django 3.0.7 on 2020-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='操作名称')),
                ('time', models.DateTimeField(verbose_name='操作时间')),
                ('value', models.BooleanField(verbose_name='操作值')),
            ],
        ),
    ]
